require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchedulesEventsController do

  # This should return the minimal set of attributes required to create a valid
  # SchedulesEvent. As you add validations to SchedulesEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "schedule_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SchedulesEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all schedules_events as @schedules_events" do
      schedules_event = SchedulesEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:schedules_events).should eq([schedules_event])
    end
  end

  describe "GET show" do
    it "assigns the requested schedules_event as @schedules_event" do
      schedules_event = SchedulesEvent.create! valid_attributes
      get :show, {:id => schedules_event.to_param}, valid_session
      assigns(:schedules_event).should eq(schedules_event)
    end
  end

  describe "GET new" do
    it "assigns a new schedules_event as @schedules_event" do
      get :new, {}, valid_session
      assigns(:schedules_event).should be_a_new(SchedulesEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested schedules_event as @schedules_event" do
      schedules_event = SchedulesEvent.create! valid_attributes
      get :edit, {:id => schedules_event.to_param}, valid_session
      assigns(:schedules_event).should eq(schedules_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchedulesEvent" do
        expect {
          post :create, {:schedules_event => valid_attributes}, valid_session
        }.to change(SchedulesEvent, :count).by(1)
      end

      it "assigns a newly created schedules_event as @schedules_event" do
        post :create, {:schedules_event => valid_attributes}, valid_session
        assigns(:schedules_event).should be_a(SchedulesEvent)
        assigns(:schedules_event).should be_persisted
      end

      it "redirects to the created schedules_event" do
        post :create, {:schedules_event => valid_attributes}, valid_session
        response.should redirect_to(SchedulesEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved schedules_event as @schedules_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchedulesEvent.any_instance.stub(:save).and_return(false)
        post :create, {:schedules_event => { "schedule_id" => "invalid value" }}, valid_session
        assigns(:schedules_event).should be_a_new(SchedulesEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchedulesEvent.any_instance.stub(:save).and_return(false)
        post :create, {:schedules_event => { "schedule_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested schedules_event" do
        schedules_event = SchedulesEvent.create! valid_attributes
        # Assuming there are no other schedules_events in the database, this
        # specifies that the SchedulesEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchedulesEvent.any_instance.should_receive(:update_attributes).with({ "schedule_id" => "1" })
        put :update, {:id => schedules_event.to_param, :schedules_event => { "schedule_id" => "1" }}, valid_session
      end

      it "assigns the requested schedules_event as @schedules_event" do
        schedules_event = SchedulesEvent.create! valid_attributes
        put :update, {:id => schedules_event.to_param, :schedules_event => valid_attributes}, valid_session
        assigns(:schedules_event).should eq(schedules_event)
      end

      it "redirects to the schedules_event" do
        schedules_event = SchedulesEvent.create! valid_attributes
        put :update, {:id => schedules_event.to_param, :schedules_event => valid_attributes}, valid_session
        response.should redirect_to(schedules_event)
      end
    end

    describe "with invalid params" do
      it "assigns the schedules_event as @schedules_event" do
        schedules_event = SchedulesEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchedulesEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedules_event.to_param, :schedules_event => { "schedule_id" => "invalid value" }}, valid_session
        assigns(:schedules_event).should eq(schedules_event)
      end

      it "re-renders the 'edit' template" do
        schedules_event = SchedulesEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchedulesEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => schedules_event.to_param, :schedules_event => { "schedule_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested schedules_event" do
      schedules_event = SchedulesEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => schedules_event.to_param}, valid_session
      }.to change(SchedulesEvent, :count).by(-1)
    end

    it "redirects to the schedules_events list" do
      schedules_event = SchedulesEvent.create! valid_attributes
      delete :destroy, {:id => schedules_event.to_param}, valid_session
      response.should redirect_to(schedules_events_url)
    end
  end

end
