require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UsersMeetingsController do

  # This should return the minimal set of attributes required to create a valid
  # UsersMeeting. As you add validations to UsersMeeting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersMeetingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all users_meetings as @users_meetings" do
      users_meeting = UsersMeeting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:users_meetings).should eq([users_meeting])
    end
  end

  describe "GET show" do
    it "assigns the requested users_meeting as @users_meeting" do
      users_meeting = UsersMeeting.create! valid_attributes
      get :show, {:id => users_meeting.to_param}, valid_session
      assigns(:users_meeting).should eq(users_meeting)
    end
  end

  describe "GET new" do
    it "assigns a new users_meeting as @users_meeting" do
      get :new, {}, valid_session
      assigns(:users_meeting).should be_a_new(UsersMeeting)
    end
  end

  describe "GET edit" do
    it "assigns the requested users_meeting as @users_meeting" do
      users_meeting = UsersMeeting.create! valid_attributes
      get :edit, {:id => users_meeting.to_param}, valid_session
      assigns(:users_meeting).should eq(users_meeting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UsersMeeting" do
        expect {
          post :create, {:users_meeting => valid_attributes}, valid_session
        }.to change(UsersMeeting, :count).by(1)
      end

      it "assigns a newly created users_meeting as @users_meeting" do
        post :create, {:users_meeting => valid_attributes}, valid_session
        assigns(:users_meeting).should be_a(UsersMeeting)
        assigns(:users_meeting).should be_persisted
      end

      it "redirects to the created users_meeting" do
        post :create, {:users_meeting => valid_attributes}, valid_session
        response.should redirect_to(UsersMeeting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved users_meeting as @users_meeting" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersMeeting.any_instance.stub(:save).and_return(false)
        post :create, {:users_meeting => { "user_id" => "invalid value" }}, valid_session
        assigns(:users_meeting).should be_a_new(UsersMeeting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UsersMeeting.any_instance.stub(:save).and_return(false)
        post :create, {:users_meeting => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested users_meeting" do
        users_meeting = UsersMeeting.create! valid_attributes
        # Assuming there are no other users_meetings in the database, this
        # specifies that the UsersMeeting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UsersMeeting.any_instance.should_receive(:update_attributes).with({ "user_id" => "MyString" })
        put :update, {:id => users_meeting.to_param, :users_meeting => { "user_id" => "MyString" }}, valid_session
      end

      it "assigns the requested users_meeting as @users_meeting" do
        users_meeting = UsersMeeting.create! valid_attributes
        put :update, {:id => users_meeting.to_param, :users_meeting => valid_attributes}, valid_session
        assigns(:users_meeting).should eq(users_meeting)
      end

      it "redirects to the users_meeting" do
        users_meeting = UsersMeeting.create! valid_attributes
        put :update, {:id => users_meeting.to_param, :users_meeting => valid_attributes}, valid_session
        response.should redirect_to(users_meeting)
      end
    end

    describe "with invalid params" do
      it "assigns the users_meeting as @users_meeting" do
        users_meeting = UsersMeeting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersMeeting.any_instance.stub(:save).and_return(false)
        put :update, {:id => users_meeting.to_param, :users_meeting => { "user_id" => "invalid value" }}, valid_session
        assigns(:users_meeting).should eq(users_meeting)
      end

      it "re-renders the 'edit' template" do
        users_meeting = UsersMeeting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UsersMeeting.any_instance.stub(:save).and_return(false)
        put :update, {:id => users_meeting.to_param, :users_meeting => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested users_meeting" do
      users_meeting = UsersMeeting.create! valid_attributes
      expect {
        delete :destroy, {:id => users_meeting.to_param}, valid_session
      }.to change(UsersMeeting, :count).by(-1)
    end

    it "redirects to the users_meetings list" do
      users_meeting = UsersMeeting.create! valid_attributes
      delete :destroy, {:id => users_meeting.to_param}, valid_session
      response.should redirect_to(users_meetings_url)
    end
  end

end
